---
version: "3.0"
services:
  gfp-frontend:
    image: lucaslive974/gfp-frontend:1.0.0
    container_name: gfp_frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - 3000:3000
    depends_on:
      - gfp-backend
    networks:
      - network
        
  gfp-backend:
    image: lucaslive974/gfp-backend:1.2.1
    container_name: gfp_backend
    volumes:
      - /GFP/app/backend/logs:/gfp/src/logs
    environment:
      - CALLBACK_DOMAIN=${CALLBACK_DOMAIN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EXPRESS_HOST=${EXPRESS_HOST}
      - EXPRESS_PORT=${EXPRESS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - REDIRECT_FRONTEND_URL=${REDIRECT_FRONTEND_URL}
      - GFP_COOKIE_DOMAIN=${GFP_COOKIE_DOMAIN}
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mysql
    networks:
      - network

  redis:
    image: redis:7.4
    restart: unless-stopped
    container_name: gfp_redis
    volumes:
      - /GFP/redis:/usr/local/etc/redis
    networks:
      - network

  mysql:
    image: mysql:9.0
    restart: unless-stopped
    container_name: gfp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPWD}
      MYSQL_DATABASE: 'gfp'
      MYSQL_USER: ${GFPUSER}
      MYSQL_PASSWORD: ${GFPPWD}
    volumes:
      - /GFP/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network

networks:
  network: